spring.datasource.url=jdbc:mysql://localhost:3306/edumatch_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

django.base-url=http://localhost:8000

jwt.secret=edumatch-secret-key-2026-muy-larga-para-seguridad
jwt.expiration=86400000

server.port=8080
spring.application.name=edumatch-api
